### ISSUE TITLE
启动报错Queue.__init__() got an unexpected keyword argument 'loop'

### ISSUE THREAD

**Issue by SlightDust** [Poppy-xiao/chronocat_to_HoshinoBot#1]
环境是Win10 + Python 3.11.4
```powershell
PS D:\chronocat_to_HoshinoBot> python .\run.py
Traceback (most recent call last):
  File "D:\chronocat_to_HoshinoBot\run.py", line 7, in <module>
    server = WebSocketServer()
             ^^^^^^^^^^^^^^^^^
  File "D:\chronocat_to_HoshinoBot\src\websocket.py", line 14, in __init__
    self.queue_satori = asyncio.Queue(loop=self.loop)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: Queue.__init__() got an unexpected keyword argument 'loop'
```

**Comment by SlightDust** [comment]
我换个低一点的python版本试试

**Comment by SlightDust** [comment]
用python3.9.10没这个问题了

**Comment by Poppy-xiao** [comment]
> 用python3.9.10没这个问题了

我看了一眼这里可以删掉里面的self.loop,更高版本就不会有问题了，代码已更新。
